version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
    - mysql:/var/lib/mysql
  superset:
    image: onthedesk/superset
    restart: always
    depends_on:
    - mysql
    - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
    ports:
      - 8088:8088
    command: "tail -f /dev/null"
    volumes:
      - .:/home/work/incubator-superset
volumes:
  mysql:
    external: false
  redis:
    external: false
